export interface PlantModel {
    id : number,
    name_fr : string,
    name_nl : string,
    name_en : string,
    name_la : string,
    description1_fr : string,
    description1_nl : string,
    description1_en : string,
    description2_fr : string,
    description2_nl : string,
    description2_en : string,
    description3_fr : string,
    description3_nl : string,
    description3_en : string,
    image : any,
    audio : any,
    mimeTypeAudio : string,
    mimeTypeImage : string,
    imageUrl : string,
    audioUrl : string,
    latitude : number,
    longitude : number,
    startDate : any,
    endDate : any,
    interval : number,
    isDeleted : boolean,
    categoryPlant_id : number,
    seasons? : number[],
    distance?:number,
    isSaved? : boolean, 
}